# Generated by Django 4.2.13 on 2024-06-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m10', '0003_rename_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
