# Generated by Django 4.2.13 on 2024-06-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m10', '0005_remove_order_total_price_order_quantity_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
