# Generated by Django 4.2.13 on 2024-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m10', '0006_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
